### ISSUE TITLE
Request to add syke9p3's Linux Mint logos

### ISSUE THREAD

**Issue by syke9p3** [alfonsusac/kawaii-logos-data#1]
I would like to add a logo I made for Linux Mint which can be found in [syke9p3's repository](https://github.com/syke9p3/Syke-VTuber-Icons/tree/main/Linux%20Mint).

<img width="400" src="https://raw.githubusercontent.com/syke9p3/Syke-VTuber-Icons/main/Linux%20Mint/Mint.png">

**Comment by alfonsusac** [comment]
wow, these are nice

**Comment by alfonsusac** [comment]
@syke9p3 permission to automatically scrape the whole repo instead?

**Comment by syke9p3** [comment]
@alfonsusac Sure sure! I forgot to mention that lol. Please do scrape the whole repo instead. Thank you

**Comment by alfonsusac** [comment]
@syke9p3 its live
https://vtuberlogos.alfon.dev/syke9p3

Commit: https://github.com/alfonsusac/kawaii-logos-data/commit/ab9fc3de1916d3f94846a8c0248e36749597afee
